# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'AkkasKhooneh' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AkkasKhooneh
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  target 'AkkasKhooneh-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AkkasKhoonehTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AkkasKhooneh-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AkkasKhooneh-tvOS

end
