export const Pages = {
  LOGIN: 'Login',
  SIGN_UP: 'SignUp',
  SIGN_UP_COMPLETE: 'SIGN_UP_COMPLETE',
  PROFILE: 'Profile',
  PROFILE_EDIT: 'ProfileEdit',
  PROFILE_SETTINGS: 'ProfileSettings',
  NEW_POST: 'NewPost',
  CHANGE_PASS: 'ChangePass',
  ADD_POST_INFO: 'AddPostInfo',
  ADD_FRIENDS: 'AddFriends',
  MAIN: 'Main',
  AUTH_STACK: 'AuthStack',
  HOME: 'Home',
  POST_INFO_PAGE: 'PostInfo',
  BOARDS_STACK: 'BoardsStack',
  BOARDS_PAGE: 'BoardsPage',
  ADD_POST_TO_BOARD: 'AddPostToBoard',
  SEARCH: 'Search',
  INSIDE: 'Inside',
  SEARCH_USER_OR_TAG: 'SearchUserOrTag',
  TAGS_PHOTOS: 'TagsPhotos',
};
