export const Pages = {
  LOGIN: 'Login',
  SIGN_UP: 'SignUp',
  SIGN_UP_COMPLETE: 'SIGN_UP_COMPLETE',
  PROFILE: 'Profile',
  PROFILE_EDIT: 'ProfileEdit',
  PROFILE_SETTINGS: 'ProfileSettings',
  NEW_POST: 'NewPost',
  CHANGE_PASS: 'ChangePass',
  ADD_POST_INFO: 'AddPostInfo',
  ADD_FRIENDS: 'AddFriends',
  MAIN: 'Main',
  AUTH_STACK: 'AuthStack',
  HOME: 'Home',
  BOARDS_PAGE: 'BoardsPage',
};
