export enum Pages {
  LOGIN = 'Login',
  SIGN_UP = 'SignUp',
  SIGN_UP_COMPLETE = 'SignUpComplete',
  SELF_PROFILE = 'Profile',
  OTHERS_PROFILE = 'OthersProfile',
  PROFILE_EDIT = 'ProfileEdit',
  PROFILE_SETTINGS = 'ProfileSettings',
  NEW_POST = 'NewPost',
  CHANGE_PASS = 'ChangePass',
  ADD_POST_INFO = 'AddPostInfo',
  ADD_FRIENDS = 'AddFriends',
  MAIN = 'Main',
  AUTH_STACK = 'AuthStack',
  HOME = 'Home',
  POST_INFO_PAGE = 'PostInfo',
  BOARDS_PAGE = 'BoardsPage',
  ADD_POST_TO_BOARD = 'AddPostToBoard',
  SEARCH = 'Search',
  INSIDE = 'Inside',
  SEARCH_USER_OR_TAG = 'SearchUserOrTag',
  TAGS_PHOTOS = 'TagsPhotos',
  CONTACT_LIST = 'ContactList',
  NOTIFICATION = 'Notification',
  FORGOT_PASSWORD = 'ForgotPassword',
  TOKEN_PAGE = 'TokenPage',
  GET_NEW_PASSWORD = 'GetNewPassword',
}
