export const Parameters = {
  USERNAME: 'USERNAME',
  EMAIL: 'EMAIL',
  PASSWORD: 'PASSWORD',
  POST_ID: 'POST_ID',
  BOARD_ID: 'BOARD_ID',
  BOARD: 'BOARD',
  TAB: 'TAB',
  IS_SELF: 'IS_SELF',
  TAG_ID: 'TAG_ID',
  TAG_NAME: 'TAG_NAME',
};
