export const Server = {
  UPDATE_USER: '/social/profile/',
  UPDATE_ACCESS_TOKEN: '/auth/token/refresh/',
  EDIT_PROFILE: '/auth/editprofile/',
  CHANGE_PROFILE_PIC: '/social/change-pic/',
  CHANGE_PASSWORD: '/auth/changepassword/',
  LOGIN_USER: '/auth/login/',
  GET_SELF_PHOTOS_NEXT_PAGE: '/social/pictures/?page=',
  GET_SELF_BOARDS_NEXT_PAGE: '/social/boards/?page=',
  GET_HOME_POSTS_NEXT_PAGE: '/social/feed/?page=',
  GET_BOARDS_DETAILS: '/social/boardsdetails/',
  CREATE_BOARD: '/social/create-new-board/',
  CHECK_EMAIL: '/auth/checkemail/',
  SIGN_UP_USER: '/auth/register/',
  SEND_POST: '/social/create-new-post/',
  ADD_POST_TO_BOARD: '/social/addnewposttoboard/',
  DELETE_BOARD: '/social/deleteboard/',
  GET_POST_INFO: '/social/post/',
  LIKE_DISLIKE: '/social/like/',
};
