export const Strings = {
    APP_NAME: 'عکاسخونه',
    EMAIL_ADDRESS: 'آدرس ایمیل',
    PASSWORD: 'رمز عبور',
    REPEAT_PASSWORD: 'تکرار رمز عبور',
    ENTER: 'ورود',
    FORGOT_PASSWORD: 'آیا رمز عبور خود را فراموش کرده‌اید؟',
    SIGN_UP: 'ثبت‌نام',
    ENTER_LOGIN_PAGE: 'ورود به برنامه',
    USER_NAME: 'نام‌کاربری',
    FIRST_LAST_NAME: 'نام و نام‌خانوادگی',
    ABOUT_YOU: 'درباره خودتون بگید',
    COMPLETE_INFO: 'تکمیل اطلاعات',
    PHOTOS: 'عکس‌ها',
    INTERESTS: 'علاقه‌مندی‌ها',
    EDIT:'ویرایش',
    SAVE_CHANGES: 'ذخیره تغییرات',
    EDIR_PROFILE: 'ویرایش پروفایل',

};