export const Strings = {
    APP_NAME: 'عکاسخونه',
    EMAIL_ADDRESS: 'آدرس ایمیل',
    PASSWORD: 'رمز عبور',
    REPEAT_PASSWORD: 'تکرار رمز عبور',
    ENTER: 'ورود',
    FORGOT_PASSWORD: 'آیا رمز عبور خود را فراموش کرده‌اید؟',
    SIGN_UP: 'ثبت‌نام',
    ENTER_LOGIN_PAGE: 'ورود به برنامه',
    USER_NAME: 'نام‌کاربری',
    FIRST_LAST_NAME: 'نام و نام‌خانوادگی',
    ABOUT_YOU: 'درباره خودتون بگید',
    COMPLETE_INFO: 'تکمیل اطلاعات',
    PHOTOS: 'عکس‌ها',
    INTERESTS: 'علاقه‌مندی‌ها',
    EDIT: 'ویرایش',
    SAVE_CHANGES: 'ذخیره تغییرات',
    EDIT_PROFILE: 'ویرایش پروفایل',
    PROFILE_SETTINGS: 'تنظیمات',
    SIGN_OUT: 'خروج از حساب کاربری',
    CHANGE_PASS: 'تغییر رمز',
    FOLLOWING: 'دنبال شده',
    FOLLOWER: 'دنبال کننده',
    SAVE_NEW_PASSWORD: 'ثبت رمز عبور جدید',
    NEW_PASSWORD: 'رمز عبور جدید',
    CURRENT_PASSWORD: 'رمز عبور فعلی',
    WRONG_CREDENTIALS: 'اطلاعات وارد شده اشتباه است.',
    EMAIL_ALREADY_EXISTS: 'ایمیل مورد نظر تکراری می باشد.',
    REPEAT_NEW_PASSWORD: 'تکرار رمز عبور جدید',
    SIGN_UP_SUCCESS: 'ثبت نام با موفقیت صورت گرفت.',
    SIGN_UP_FAIL: 'ثبت نام با خطا مواجه شد.',
    EDIT_PROFILE_SUCCESS: 'پروفایل با موفقیت ویرایش یافت.',
    EDIT_PROFILE_FAIL: 'ویرایش پروفایل با خطا مواجه شد.',
    CHANGE_PROFILE_PIC_SUCCESS: 'عکس پروفایل با موفقیت ویرایش یافت.',
    CHANGE_PROFILE_PIC_FAIL: 'ویرایش عکس پروفایل با خطا مواجه شد.',
    CHANGE_PASS_SUCCESS: 'رمز عبور با موفقیت تغییر یافت.',
    CHANGE_PASS_FAIL: 'تغییر رمز عبور با خطا مواجه شد.',
    PHOTO_GALLERY: 'گالری تصاویر',
    COMMIT_INFO: 'ثبت توضیح',
    PICTURE_INFO: 'توضیحات عکس',
    LOCATION: 'موقعیت',
    ADD_TAG: 'اضافه کردن تگ',
    ADD_POST: 'ارسال پست',
    NEXT_LEVEL: 'مرحله بعد',
    INVITE_FRIENDS: 'دعوت از دوستان',
    SEARCH_CONTACT: 'جستجوی مخاطب',
    INVITE: 'دعوت',
    SAVE_POST_INFO: 'ثبت توضیحات',
    POST_INFO: 'توضیحات عکس',
    LOCATION: 'موقعیت',
    ADD_TAGS: 'اضافه کردن تگ',
};