export const Strings = {
    APP_NAME: 'app_name',
    EMAIL_ADDRESS: 'email_address',
    PASSWORD: 'password',
    REPEAT_PASSWORD: 'repeat_password',
    LOGIN: 'login',
    FORGOT_PASSWORD: 'forgot_password',
    SIGN_UP: 'sign_up',
    ENTER_LOGIN_PAGE: 'enter_login_page',
    USERNAME: 'username',
    FIRST_LAST_NAME: 'نام و نام‌خانوادگی',
    ABOUT_YOU: 'about_you',
    COMPLETE_INFO: 'complete_info',
    PHOTOS: 'photos',
    INTERESTS: 'interests',
    EDIT: 'ویرایش',
    SAVE_CHANGES: 'ذخیره تغییرات',
    EDIT_PROFILE: 'ویرایش پروفایل',
    PROFILE_SETTINGS: 'تنظیمات',
    SIGN_OUT: 'خروج از حساب کاربری',
    CHANGE_PASS: 'تغییر رمز',
    FOLLOWING: 'دنبال شده',
    FOLLOWER: 'دنبال کننده',
    SAVE_NEW_PASSWORD: 'ثبت رمز عبور جدید',
    NEW_PASSWORD: 'رمز عبور جدید',
    CURRENT_PASSWORD: 'رمز عبور فعلی',
    WRONG_CREDENTIALS: 'اطلاعات وارد شده اشتباه است.',
    EMAIL_ALREADY_EXISTS: 'ایمیل مورد نظر تکراری می باشد.',
    REPEAT_NEW_PASSWORD: 'تکرار رمز عبور جدید',
    SIGN_UP_SUCCESS: 'ثبت نام با موفقیت صورت گرفت.',
    SIGN_UP_FAIL: 'ثبت نام با خطا مواجه شد.',
    EDIT_PROFILE_SUCCESS: 'پروفایل با موفقیت ویرایش یافت.',
    EDIT_PROFILE_FAIL: 'ویرایش پروفایل با خطا مواجه شد.',
    CHANGE_PROFILE_PIC_SUCCESS: 'عکس پروفایل با موفقیت ویرایش یافت.',
    CHANGE_PROFILE_PIC_FAIL: 'ویرایش عکس پروفایل با خطا مواجه شد.',
    CHANGE_PASS_SUCCESS: 'رمز عبور با موفقیت تغییر یافت.',
    CHANGE_PASS_FAIL: 'تغییر رمز عبور با خطا مواجه شد.',
    PHOTO_GALLERY: 'گالری تصاویر',
    COMMIT_INFO: 'ثبت توضیح',
    DESCRIPTION: 'description',
    LOCATION: 'موقعیت',
    ADD_TAG: 'اضافه کردن تگ',
    ADD_POST: 'ارسال پست',
    NEXT_LEVEL: 'مرحله بعد',
    INVITE_FRIENDS: 'دعوت از دوستان',
    SEARCH_CONTACT: 'جستجوی مخاطب',
    INVITE: 'دعوت',
    SAVE_POST_INFO: 'ثبت توضیحات',
    POST_INFO: 'توضیحات عکس',
    ADD_TAGS: 'اضافه کردن تگ',
    SEND_POST: 'ارسال پست',
    ALL: 'all',
    PICTURE_QUANTITY: 'picture_quantity',
    ADD_TO_INTERESTS: 'اضافه به علاقه‌مندی‌ها',
    CREATE_NEW_BOARD: 'ساخت برد جدید',
    CREATE_NEW_BOARD_SUCCESS: 'برد جدید با موفقیت ساخته شد.',
    CREATE_NEW_BOARD_FAIL: 'ساخت برد با خطا مواجه شد.',
    CHOOSE_A_BOARD: 'یکی از بوردهای زیر را انتخاب کنید.',
};